### ISSUE TITLE
LUA ERROR: [string "app/module/RichLabel.lua"]:179: attempt to call global 'ifnil' (a nil value)

### ISSUE THREAD

**Issue by zick-elephant** [ayongm2/RichLabel#1]
LUA ERROR: [string "app/module/RichLabel.lua"]:179: attempt to call global 'ifnil' (a nil value)

**Comment by zick-elephant** [comment]
[LUA-print] LUA ERROR: [string "app/module/RichLabel.lua"]:195: attempt to call field 'isnotempty' (a nil value)

**Comment by zick-elephant** [comment]
LUA ERROR: [string "app/module/RichLabel.lua"]:180: attempt to index field 'size' (a nil value)
local rl = RichLabel.new([[<default color=#00ff00 size=20 width=100/>这样<text 
				color=#ff0000 size=30 clickable=true shadow_color=#ffffff00 tag=10
				shadow_blur=2 shadow_offset_x=2 shadow_offset_y=-2>能</text><image 
				clickable=true name=a10>demo/RadioButtonOn.png</image><br>哈哈]])
                :addTo(self):center()
                :onClick(function ( node, params )
                    dump(params)
                end)
    rl:foreachElements(function ( node, tag )
            node:runAction(cc.RepeatForever:create(transition.sequence{
                cc.FadeOut:create(0.5),
                cc.FadeIn:create(0.5)
            }))
        end, 10, "a10")

**Comment by zick-elephant** [comment]
[LUA-print] LUA ERROR: [string "framework/shortcodes.lua"]:69: attempt to call method 'addChild' (a nil value)

self.rl = RichLabel.new{ignoreSize = false, size = cc.size(750, 667)}
	self.rl:addTo(self)
    self.rl:insertElement({text = "我", color = cc.c3b(255, 0, 0), size = 16, clickable = false})

**Comment by ayongm2** [comment]
第一次被提issue,有种莫名的喜感~~
前三个是定义在我的util.lua里,剥离出来时没弄好,本地测试却正常,所以没能发现,非常感谢!
第四个我这没问题,有更多错误信息才能知道,不知道能否多提供点log,另外用insertElement方式需要手动调下refresh.

**Comment by zick-elephant** [comment]
最近在git上找找文字相关的东西用，我用的版本是quick3.3，这个addChild问题来得很奇怪,不知道你是什么版本，感觉是richlabel new了之后被清除了还是继承失败没有这个方法

**Comment by ayongm2** [comment]
我也是用quick3.3,我试了你上面的代码,后面加上句refresh,self是当前scene,没有什么问题,你现在还能重现吗,能的话把完整log放上来看看吧

**Comment by zick-elephant** [comment]
addChild的问题搞定了，是我没有添加到scene上，但是又有新的问题:
[LUA-print] LUA ERROR: [string "app/module/RichLabel.lua"]:457: attempt to call method 'alignParent' (a nil value)

function Game:initRichLabel()
	self.rl = RichLabel.new{ignoreSize = false, size = cc.size(750, 667)}
	self.rl:addTo(self.stage_)
	self.rl:insertElement({text = "我", color = cc.c3b(255, 0, 0), size = 16, clickable = false})
	self.rl:refresh()
end

**Comment by ayongm2** [comment]
还是我封装的方法的问题,改成通常写法了

**Comment by zick-elephant** [comment]
经测试，\n只能单独insertElement才行，写在句子中间就工作不正常，是这样吗

**Comment by ayongm2** [comment]
不用啊,写在句子中间也正常啊,我下面这个测试是正常的.
local rl = RichLabel.new{ignoreSize = false, size = cc.size(100, 0) }
    rl:insertElement({text = "我\n无效吗", color = cc.c3b(255, 0, 0), size = 16, clickable = true})
    rl:insertElement({text = "\n", color = cc.c3b(255, 0, 0), size = 16})
    rl:insertElement({text = "也", color = cc.c3b(0, 255, 0), size = 18, shadow = {color = cc.c4b(0, 0, 0, 255), blur = 2, offset = cc.size(2, -2)} })
    rl:addTo(self):center()
    rl:refresh()

**Comment by zick-elephant** [comment]
self.game_:insertElementToRL({text = "饥饿...饥饿...\n", color = cc.c3b(255, 255, 255), size = 30})
	self.game_:insertElementToRL({text = "\n", color = cc.c3b(255, 0, 0), size = 16})
	self.game_:insertElementToRL({text = "\n饥饿...饥饿...", color = cc.c3b(255, 255, 255), size = 30})

我是这样测的，只一三会出现阶梯式。去掉一二的\n时，第三个无效。我在Mac上的quick player测的，不知道在手机上会不会不一样。

**Comment by ayongm2** [comment]
好像是这样,有空查一下...

**Comment by ayongm2** [comment]
不好意思,拖了好久,结果是其实是有效果的,如果改为顶对齐你就会发现,用insertElement方式是一个块一个块的加入,并没有主动分析改成一行的方式,你可以用伪html的书写方式来写,其实也是更推荐用这种方式,当初写这个也是为什么服务端传来直接能显示...如果要在insertElement方式下改成可解析的方式,也是根据\n来分成多个元素加入,和手工写成只有一个\n的方式一样

**Comment by zick-elephant** [comment]
嗯👌，我先继续试试，有问题我再讲
